### ISSUE TITLE
search result

### ISSUE THREAD

**Issue by Zhu-Siqi** [maovshao/PLMSearch#1]
Hi, thanks for your intersting work! Could you release your roc result (for example https://github.com/steineggerlab/foldseek-analysis/blob/main/multidomain_benchmark/PLOTS/FIG2/foldseek.rocx)? It will save the time of running structure-based alignment methods and make your work easy to follow , especially on your new dataset!

**Comment by Zhu-Siqi** [comment]
I got it. Sorry for my question! 

Maybe, I think it will be better to show that link in your readme file.

**Comment by maovshao** [comment]
Glad your problem is solved. 

You can reproduce all our experiments with good visualization by following the steps in [main.ipynb](https://github.com/maovshao/PLMSearch/blob/main/main.ipynb).

Also, We have released our experiment data in [plmsearch_data](https://dmiip.sjtu.edu.cn/PLMSearch/static/download/plmsearch_data.tar.gz).

Hope these instruction help.
