### ISSUE TITLE
Using UniRef50 for searching is too slow that it fails to complete the search process.

### ISSUE THREAD

**Issue by changweioy** [maovshao/PLMSearch#5]
I've locally built the UniRef50 database (with embedding.pkl at 340 GB and uniref50.fasta at 26 GB) and attempted to perform sequence alignments using it. When executing the pickle.load operation in main_similarity.py to load the database, it takes **several hours** and consumes over 700 GB of memory. The subsequent search process is even slower, to the point where it doesn't complete. However, using your web server for the same search task finishes in just **a few minutes**. Are the codes running on the web server different from those on GitHub? Could you provide insights into the size of the UniRef50 database used on your server and any optimization suggestions?

**Comment by changweioy** [comment]
log:
![failed](https://github.com/maovshao/PLMSearch/assets/9460156/88cd2bcb-e3e2-4d38-814e-faeb12ba0e10)

**Comment by maovshao** [comment]
1. Our Web server doesn't have that much GPU memory, so we do the calculations on CPU and RAM.

2. Also, as you tried, loading embedding.pkl each time is very time-consuming, so try to load it once and do all the work afterwards (our server only loads it when it starts, so users don't have to reload embedding.pkl when searching)

3. The amount of memory used depends a lot on your query/target size. Obviously, when you want to search UniRef50 as a target, you need to reduce your query size. I think setting the batch size is a very good strategy, instead of searching all queries once.
 
4. In addition, you can set a similarity threshold or select only the top-N search results with the highest similarity for subsequent sorting and other processing to speed up.

If you find these suggestions useful to you, don't forget to star or fork this repository.

Best.
