### ISSUE TITLE
Cannot download plmsearch_data.tar.gz without SJTU VPN

### ISSUE THREAD

**Issue by batmen-lab** [maovshao/PLMSearch#6]
Hi, 

I cannot download https://dmiip.sjtu.edu.cn/PLMSearch/static/download/plmsearch_data.tar.gz without SJTU VPN. 
Neither does https://dmiip.sjtu.edu.cn/PLMAlign/static/download/plmalign_data.tar.gz. 
The error I encountered is 403 error.

Could you provide an alternative downloadable link to the the data using Google Drive/Dropbox/Baidu Pan? Thanks!

![image](https://github.com/maovshao/PLMSearch/assets/106487150/f160429b-1c0f-4425-b200-acaf92813d58)

**Comment by changweioy** [comment]
The webserver is also inaccessible now.

**Comment by maovshao** [comment]
Sorry for the late reply due to the update of GitHubs of PLMSearch and PLMAlign.

Due to some reasons, the above requirements will exist for accessing the PLMSearch (PLMAlign) server or downloading datasets **this week**, **and will be fully restored to normal in a week** (i.e., access without SJTU VPN).

In addition, I have uploaded the data of PLMSearch and PLMAlign to **Zenodo (https://zenodo.org/records/11480660)** in today's update, please check the latest updates of the two GitHubs. Enjoy it.

At the same time, I will keep this issue open until the Web server is restored to normal.

Best.

**Comment by batmen-lab** [comment]
Thanks! The Zenodo link works!

**Comment by JinyuanSun** [comment]
the server https://dmiip.sjtu.edu.cn/PLMSearch is not working again.

**Comment by maovshao** [comment]
Thanks for the heads up, I think it works now.

By the way, we check the status of the server from time to time. When I update the web server and restart it (occasionally and cautiously), it often takes 3-4 hours for the server to reload. So, "Check it later" will help.

Best.
